version: '3.10.7'
services:
  web:
    build: .
    container_name: weather_api
    command: python manage.py runserver 0.0.0.0:8181
    volumes:
      - .:/app
    ports:
      - "8181:8181"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_cache

  test:
    build: .
    command: pytest
    depends_on:
      - web
      - redis

