# Generated by Django 5.0.6 on 2025-05-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_ip", models.GenericIPAddressField()),
                ("city", models.CharField(max_length=100)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "unique_together": {("user_ip", "city")},
            },
        ),
    ]
