# Generated by Django 5.0.6 on 2025-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_searchhistory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchhistory",
            name="user_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
